FROM ubuntu
#Para evitar utilizar o cache colocar os comandos em uma linha
RUN apt update && apt install curl --yes
#RUN apt update
#RUN apt install curl --yes
#RUN apt insall net-tools --yes
#RUN apt install vim --yes